##  A MAKEFILE FOR Ancestry HMM. TO USE, RUN THE COMMAND "make" VIA COMMAND LINE ##
## This is super-broken right now. 

all:
	g++-11 -O3 -o ancestry_hmm -fopenmp ancestry_hmm.cpp -L /opt/homebrew/Cellar/armadillo/10.8.0/lib/ -I /opt/homebrew/Cellar/armadillo/10.8.0/include/ -larmadillo

